#
# Macro file for "Hadr07.cc"
#
/control/verbose 1
/run/verbose 1
#
/testhadr/det/setIsotopeMat tritium 1 3 0.1 g/cm3
#
/testhadr/det/setNbOfAbsor  1
/testhadr/det/setAbsor 1 tritium  1 mm
/testhadr/det/setSizeYZ 1 mm
#
/process/em/verbose 0
/process/had/verbose 0
#
/run/initialize
#
/process/inactivate hadElastic
/process/eLoss/StepFunctionLightIons 0.2 10 nm
/process/em/printParameters
#
/gps/particle deuteron
/gps/energy 400 keV
#
/run/printProgress 100000
/run/beamOn 1000000
